name: actions

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with: 
          deno-version: v1.44.4
      - run: deno fmt --check
      - run: deno lint
